AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template for the countdown API
Resources:
  ApiGatewayApi:
      Type: AWS::Serverless::Api
      Properties:
        DefinitionUri: ./swagger.yaml
        StageName: Prod
        Variables:
          # NOTE: Before using this template, replace the <<region>> and <<account>> fields
          #       in Lambda integration URI in the swagger file to region and accountId 
          #       you are deploying to
          LambdaFunctionName: !Ref countdown
  countdown:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'handler.handler'
      Runtime: nodejs6.10
      CodeUri: ./
      Description: ''
      MemorySize: 512
      Timeout: 3
      Events:
        CountdownApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /countdown/{letters}
            Method: GET