swagger: "2.0"
info:
  version: "1.0"
  title: "countdown-stack-swagger"
host: "el1lwut6el.execute-api.eu-west-2.amazonaws.com"
basePath: "/Prod"
schemes:
- "https"
paths:
  /countdown/{letters}:
    get:
      responses: {}
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:eu-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-2:613053500835:function:countdown-stack-countdown-1CDUB0MRLY8WH/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
